"""protoc-generated wire types and gRPC stubs for the Yutha control plane.

This package is regenerated by ``scripts/codegen.py`` from the canonical
``.proto`` files under ``/spec/`` at the repo root. Everything inside
``_proto/`` except this module is generated; don't edit by hand.

End-users normally don't import directly from here — the top-level
``yutha`` package re-exports the ergonomic Pydantic models and the
``YuthaClient`` that wraps the gRPC stubs. Direct access is available for
escape hatches (custom interceptors, raw RPC calls, conformance tests).

Submodules:

- :mod:`yutha._proto.common_pb2` — shared types (AgentId, Hash, etc.)
- :mod:`yutha._proto.passport.passport_v1_pb2` — Passport, registration
- :mod:`yutha._proto.envelope.envelope_v1_pb2` — Envelope, performatives
- :mod:`yutha._proto.receipt.receipt_v1_pb2` — Receipt, evidence, seal
- :mod:`yutha._proto.capability.capability_v1_pb2` — Capability, scopes, caveats
- :mod:`yutha._proto.topology.topology_v1_pb2` — Topology, admission, sybil
- :mod:`yutha._proto.control_plane.v1_pb2` — control-plane request/response
- :mod:`yutha._proto.control_plane.v1_pb2_grpc` — AdmissionService,
  CapabilityService, EnvelopeService, ReceiptService client + server
  stubs
"""
