# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from yutha._proto.control_plane import v1_pb2 as control__plane_dot_v1__pb2

GRPC_GENERATED_VERSION = '1.81.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in control_plane/v1_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AdmissionServiceStub:
    """---------------------------------------------------------------------------
    AdmissionService — registry-facing operations
    ---------------------------------------------------------------------------

    AdmissionService handles agent lifecycle: register at swarm join,
    rotate keys, revoke. Also exposes the swarm topology (immutable for
    the swarm's lifetime — agents fetch it once and cache).
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Register = channel.unary_unary(
                '/yutha.control_plane.v1.AdmissionService/Register',
                request_serializer=control__plane_dot_v1__pb2.RegisterRequest.SerializeToString,
                response_deserializer=control__plane_dot_v1__pb2.RegisterResponse.FromString,
                _registered_method=True)
        self.Revoke = channel.unary_unary(
                '/yutha.control_plane.v1.AdmissionService/Revoke',
                request_serializer=control__plane_dot_v1__pb2.RevokeRequest.SerializeToString,
                response_deserializer=control__plane_dot_v1__pb2.RevokeResponse.FromString,
                _registered_method=True)
        self.OperatorRevoke = channel.unary_unary(
                '/yutha.control_plane.v1.AdmissionService/OperatorRevoke',
                request_serializer=control__plane_dot_v1__pb2.OperatorRevokeRequest.SerializeToString,
                response_deserializer=control__plane_dot_v1__pb2.OperatorRevokeResponse.FromString,
                _registered_method=True)
        self.RotateKey = channel.unary_unary(
                '/yutha.control_plane.v1.AdmissionService/RotateKey',
                request_serializer=control__plane_dot_v1__pb2.RotateKeyRequest.SerializeToString,
                response_deserializer=control__plane_dot_v1__pb2.RotateKeyResponse.FromString,
                _registered_method=True)
        self.GetTopology = channel.unary_unary(
                '/yutha.control_plane.v1.AdmissionService/GetTopology',
                request_serializer=control__plane_dot_v1__pb2.GetTopologyRequest.SerializeToString,
                response_deserializer=control__plane_dot_v1__pb2.GetTopologyResponse.FromString,
                _registered_method=True)


class AdmissionServiceServicer:
    """---------------------------------------------------------------------------
    AdmissionService — registry-facing operations
    ---------------------------------------------------------------------------

    AdmissionService handles agent lifecycle: register at swarm join,
    rotate keys, revoke. Also exposes the swarm topology (immutable for
    the swarm's lifetime — agents fetch it once and cache).
    """

    def Register(self, request, context):
        """Register an agent presenting a signed passport. The control plane
        verifies the passport's self-signature, evaluates admission policy
        against the topology, and (on accept) produces an `agent.register`
        receipt. The response carries the receipt id; the agent can fetch
        the receipt via ReceiptService.Get.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Revoke(self, request, context):
        """Self-revoke an agent. The caller MUST present an
        `AgentBearerToken` whose agent_id matches `RevokeRequest.agent_id`
        (cross-agent revocation on this RPC is refused with
        `PERMISSION_DENIED`). Produces an `agent.revoke` receipt and
        triggers active-stream tear-down (RFC 0009 §3.3) — the caller's
        own subscribe streams close and subsequent bearer tokens reject.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def OperatorRevoke(self, request, context):
        """Operator-level eviction of an agent. The caller MUST present an
        `OperatorBearerToken` (see RFC 0009). Produces an
        `agent.operator_revoke` receipt (distinct from `agent.revoke`
        for audit clarity) and triggers the same active-stream tear-down
        on the target. When `cascade_capabilities` is true, every
        capability issued by or held by the target is also revoked with
        a `capability.revoke` receipt per cap.

        Returns `FAILED_PRECONDITION: operator credentials not enabled`
        if the server was started without `--operator-public-key`.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RotateKey(self, request, context):
        """Rotate an agent's signing key. Produces an `agent.rotate_key`
        receipt. Future tokens / envelopes / capabilities signed by the
        agent MUST use the new key starting from the receipt's monotonic_ns.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTopology(self, request, context):
        """Get the topology of the swarm this control plane manages. Topology
        is immutable for a swarm's lifetime; agents call this once at
        startup and cache the result.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AdmissionServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Register': grpc.unary_unary_rpc_method_handler(
                    servicer.Register,
                    request_deserializer=control__plane_dot_v1__pb2.RegisterRequest.FromString,
                    response_serializer=control__plane_dot_v1__pb2.RegisterResponse.SerializeToString,
            ),
            'Revoke': grpc.unary_unary_rpc_method_handler(
                    servicer.Revoke,
                    request_deserializer=control__plane_dot_v1__pb2.RevokeRequest.FromString,
                    response_serializer=control__plane_dot_v1__pb2.RevokeResponse.SerializeToString,
            ),
            'OperatorRevoke': grpc.unary_unary_rpc_method_handler(
                    servicer.OperatorRevoke,
                    request_deserializer=control__plane_dot_v1__pb2.OperatorRevokeRequest.FromString,
                    response_serializer=control__plane_dot_v1__pb2.OperatorRevokeResponse.SerializeToString,
            ),
            'RotateKey': grpc.unary_unary_rpc_method_handler(
                    servicer.RotateKey,
                    request_deserializer=control__plane_dot_v1__pb2.RotateKeyRequest.FromString,
                    response_serializer=control__plane_dot_v1__pb2.RotateKeyResponse.SerializeToString,
            ),
            'GetTopology': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTopology,
                    request_deserializer=control__plane_dot_v1__pb2.GetTopologyRequest.FromString,
                    response_serializer=control__plane_dot_v1__pb2.GetTopologyResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'yutha.control_plane.v1.AdmissionService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('yutha.control_plane.v1.AdmissionService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AdmissionService:
    """---------------------------------------------------------------------------
    AdmissionService — registry-facing operations
    ---------------------------------------------------------------------------

    AdmissionService handles agent lifecycle: register at swarm join,
    rotate keys, revoke. Also exposes the swarm topology (immutable for
    the swarm's lifetime — agents fetch it once and cache).
    """

    @staticmethod
    def Register(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/yutha.control_plane.v1.AdmissionService/Register',
            control__plane_dot_v1__pb2.RegisterRequest.SerializeToString,
            control__plane_dot_v1__pb2.RegisterResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Revoke(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/yutha.control_plane.v1.AdmissionService/Revoke',
            control__plane_dot_v1__pb2.RevokeRequest.SerializeToString,
            control__plane_dot_v1__pb2.RevokeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def OperatorRevoke(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/yutha.control_plane.v1.AdmissionService/OperatorRevoke',
            control__plane_dot_v1__pb2.OperatorRevokeRequest.SerializeToString,
            control__plane_dot_v1__pb2.OperatorRevokeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RotateKey(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/yutha.control_plane.v1.AdmissionService/RotateKey',
            control__plane_dot_v1__pb2.RotateKeyRequest.SerializeToString,
            control__plane_dot_v1__pb2.RotateKeyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetTopology(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/yutha.control_plane.v1.AdmissionService/GetTopology',
            control__plane_dot_v1__pb2.GetTopologyRequest.SerializeToString,
            control__plane_dot_v1__pb2.GetTopologyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class CapabilityServiceStub:
    """---------------------------------------------------------------------------
    CapabilityService — issue, attenuate, revoke, check
    ---------------------------------------------------------------------------

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Issue = channel.unary_unary(
                '/yutha.control_plane.v1.CapabilityService/Issue',
                request_serializer=control__plane_dot_v1__pb2.IssueCapabilityRequest.SerializeToString,
                response_deserializer=control__plane_dot_v1__pb2.IssueCapabilityResponse.FromString,
                _registered_method=True)
        self.Attenuate = channel.unary_unary(
                '/yutha.control_plane.v1.CapabilityService/Attenuate',
                request_serializer=control__plane_dot_v1__pb2.AttenuateRequest.SerializeToString,
                response_deserializer=control__plane_dot_v1__pb2.AttenuateResponse.FromString,
                _registered_method=True)
        self.Revoke = channel.unary_unary(
                '/yutha.control_plane.v1.CapabilityService/Revoke',
                request_serializer=control__plane_dot_v1__pb2.RevokeCapabilityRequest.SerializeToString,
                response_deserializer=control__plane_dot_v1__pb2.RevokeCapabilityResponse.FromString,
                _registered_method=True)
        self.Check = channel.unary_unary(
                '/yutha.control_plane.v1.CapabilityService/Check',
                request_serializer=control__plane_dot_v1__pb2.CheckRequest.SerializeToString,
                response_deserializer=control__plane_dot_v1__pb2.CheckResponse.FromString,
                _registered_method=True)


class CapabilityServiceServicer:
    """---------------------------------------------------------------------------
    CapabilityService — issue, attenuate, revoke, check
    ---------------------------------------------------------------------------

    """

    def Issue(self, request, context):
        """Issue a new (root or attenuated) capability. Issuer authority is
        checked against the bearer token: operators can mint root caps;
        agents can attenuate from caps they hold.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Attenuate(self, request, context):
        """Attenuate an existing capability into a more restricted child. The
        child's scope is intersected with the parent's, caveats are
        additive, and `valid_until` cannot exceed the parent's.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Revoke(self, request, context):
        """Revoke a capability. Effective immediately for the control plane's
        own checks; propagation to federation peers is on a TTL.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Check(self, request, context):
        """Check whether a (capability, action) pair is permitted. Stateless,
        deterministic. Mostly used by SDKs for client-side pre-flight; the
        control plane still re-checks on every Send.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CapabilityServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Issue': grpc.unary_unary_rpc_method_handler(
                    servicer.Issue,
                    request_deserializer=control__plane_dot_v1__pb2.IssueCapabilityRequest.FromString,
                    response_serializer=control__plane_dot_v1__pb2.IssueCapabilityResponse.SerializeToString,
            ),
            'Attenuate': grpc.unary_unary_rpc_method_handler(
                    servicer.Attenuate,
                    request_deserializer=control__plane_dot_v1__pb2.AttenuateRequest.FromString,
                    response_serializer=control__plane_dot_v1__pb2.AttenuateResponse.SerializeToString,
            ),
            'Revoke': grpc.unary_unary_rpc_method_handler(
                    servicer.Revoke,
                    request_deserializer=control__plane_dot_v1__pb2.RevokeCapabilityRequest.FromString,
                    response_serializer=control__plane_dot_v1__pb2.RevokeCapabilityResponse.SerializeToString,
            ),
            'Check': grpc.unary_unary_rpc_method_handler(
                    servicer.Check,
                    request_deserializer=control__plane_dot_v1__pb2.CheckRequest.FromString,
                    response_serializer=control__plane_dot_v1__pb2.CheckResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'yutha.control_plane.v1.CapabilityService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('yutha.control_plane.v1.CapabilityService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CapabilityService:
    """---------------------------------------------------------------------------
    CapabilityService — issue, attenuate, revoke, check
    ---------------------------------------------------------------------------

    """

    @staticmethod
    def Issue(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/yutha.control_plane.v1.CapabilityService/Issue',
            control__plane_dot_v1__pb2.IssueCapabilityRequest.SerializeToString,
            control__plane_dot_v1__pb2.IssueCapabilityResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Attenuate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/yutha.control_plane.v1.CapabilityService/Attenuate',
            control__plane_dot_v1__pb2.AttenuateRequest.SerializeToString,
            control__plane_dot_v1__pb2.AttenuateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Revoke(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/yutha.control_plane.v1.CapabilityService/Revoke',
            control__plane_dot_v1__pb2.RevokeCapabilityRequest.SerializeToString,
            control__plane_dot_v1__pb2.RevokeCapabilityResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Check(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/yutha.control_plane.v1.CapabilityService/Check',
            control__plane_dot_v1__pb2.CheckRequest.SerializeToString,
            control__plane_dot_v1__pb2.CheckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class EnvelopeServiceStub:
    """---------------------------------------------------------------------------
    EnvelopeService — typed messaging
    ---------------------------------------------------------------------------

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Send = channel.unary_unary(
                '/yutha.control_plane.v1.EnvelopeService/Send',
                request_serializer=control__plane_dot_v1__pb2.SendEnvelopeRequest.SerializeToString,
                response_deserializer=control__plane_dot_v1__pb2.SendEnvelopeResponse.FromString,
                _registered_method=True)
        self.Subscribe = channel.unary_stream(
                '/yutha.control_plane.v1.EnvelopeService/Subscribe',
                request_serializer=control__plane_dot_v1__pb2.SubscribeRequest.SerializeToString,
                response_deserializer=control__plane_dot_v1__pb2.SubscribedEnvelope.FromString,
                _registered_method=True)


class EnvelopeServiceServicer:
    """---------------------------------------------------------------------------
    EnvelopeService — typed messaging
    ---------------------------------------------------------------------------

    """

    def Send(self, request, context):
        """Submit a signed envelope for delivery. The control plane:
        1. Verifies the envelope's actor signature against the agent's
        registered passport public key.
        2. Capability-checks the action (envelope.send) against the
        agent's held capabilities.
        3. Persists an `envelope.send` receipt.
        4. Forwards to the recipient's subscribe stream (if any).
        5. On successful delivery, persists an `envelope.deliver` receipt.

        The response carries the send-receipt id immediately; the
        deliver-receipt arrives asynchronously and can be polled via
        ReceiptService.Query.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Subscribe(self, request, context):
        """Subscribe to envelopes addressed to the calling agent. The stream
        stays open; envelopes arrive as they are delivered to the agent.
        Cancelling the stream means "I'm no longer subscribed" — the
        control plane stops forwarding and may buffer per the topology's
        delivery policy.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_EnvelopeServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Send': grpc.unary_unary_rpc_method_handler(
                    servicer.Send,
                    request_deserializer=control__plane_dot_v1__pb2.SendEnvelopeRequest.FromString,
                    response_serializer=control__plane_dot_v1__pb2.SendEnvelopeResponse.SerializeToString,
            ),
            'Subscribe': grpc.unary_stream_rpc_method_handler(
                    servicer.Subscribe,
                    request_deserializer=control__plane_dot_v1__pb2.SubscribeRequest.FromString,
                    response_serializer=control__plane_dot_v1__pb2.SubscribedEnvelope.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'yutha.control_plane.v1.EnvelopeService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('yutha.control_plane.v1.EnvelopeService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class EnvelopeService:
    """---------------------------------------------------------------------------
    EnvelopeService — typed messaging
    ---------------------------------------------------------------------------

    """

    @staticmethod
    def Send(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/yutha.control_plane.v1.EnvelopeService/Send',
            control__plane_dot_v1__pb2.SendEnvelopeRequest.SerializeToString,
            control__plane_dot_v1__pb2.SendEnvelopeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Subscribe(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/yutha.control_plane.v1.EnvelopeService/Subscribe',
            control__plane_dot_v1__pb2.SubscribeRequest.SerializeToString,
            control__plane_dot_v1__pb2.SubscribedEnvelope.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class ReceiptServiceStub:
    """---------------------------------------------------------------------------
    ReceiptService — read access to the audit log
    ---------------------------------------------------------------------------

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Get = channel.unary_unary(
                '/yutha.control_plane.v1.ReceiptService/Get',
                request_serializer=control__plane_dot_v1__pb2.GetReceiptRequest.SerializeToString,
                response_deserializer=control__plane_dot_v1__pb2.GetReceiptResponse.FromString,
                _registered_method=True)
        self.Query = channel.unary_unary(
                '/yutha.control_plane.v1.ReceiptService/Query',
                request_serializer=control__plane_dot_v1__pb2.QueryReceiptsRequest.SerializeToString,
                response_deserializer=control__plane_dot_v1__pb2.QueryReceiptsResponse.FromString,
                _registered_method=True)


class ReceiptServiceServicer:
    """---------------------------------------------------------------------------
    ReceiptService — read access to the audit log
    ---------------------------------------------------------------------------

    """

    def Get(self, request, context):
        """Fetch a single receipt by content-address.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Query(self, request, context):
        """Run a structured query against the receipt store. Supports the same
        query variants as the receipt store trait (by-id, by-predecessor,
        by-agent, by-action-kind, by-time-range), with keyset pagination
        via opaque page tokens.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ReceiptServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Get': grpc.unary_unary_rpc_method_handler(
                    servicer.Get,
                    request_deserializer=control__plane_dot_v1__pb2.GetReceiptRequest.FromString,
                    response_serializer=control__plane_dot_v1__pb2.GetReceiptResponse.SerializeToString,
            ),
            'Query': grpc.unary_unary_rpc_method_handler(
                    servicer.Query,
                    request_deserializer=control__plane_dot_v1__pb2.QueryReceiptsRequest.FromString,
                    response_serializer=control__plane_dot_v1__pb2.QueryReceiptsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'yutha.control_plane.v1.ReceiptService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('yutha.control_plane.v1.ReceiptService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ReceiptService:
    """---------------------------------------------------------------------------
    ReceiptService — read access to the audit log
    ---------------------------------------------------------------------------

    """

    @staticmethod
    def Get(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/yutha.control_plane.v1.ReceiptService/Get',
            control__plane_dot_v1__pb2.GetReceiptRequest.SerializeToString,
            control__plane_dot_v1__pb2.GetReceiptResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Query(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/yutha.control_plane.v1.ReceiptService/Query',
            control__plane_dot_v1__pb2.QueryReceiptsRequest.SerializeToString,
            control__plane_dot_v1__pb2.QueryReceiptsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class ConstitutionServiceStub:
    """---------------------------------------------------------------------------
    ConstitutionService — operator publishes constitutions; agents query them
    ---------------------------------------------------------------------------

    The constitution layer (RFCs 0010-0013) lives one layer above
    capabilities: capabilities answer "who has authority"; constitutions
    answer "what authority is permitted to be exercised right now by this
    principal under our norms." Activate publishes a freshly-authored
    constitution; the active constitution is what EnvelopeService.Send
    + CapabilityService.Issue / Attenuate / Revoke evaluate against.

    Authorization: Activate requires an OperatorBearerToken (RFC 0009);
    GetActive requires any AgentBearerToken (registered agents need to
    know what they're bound to).

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Activate = channel.unary_unary(
                '/yutha.control_plane.v1.ConstitutionService/Activate',
                request_serializer=control__plane_dot_v1__pb2.ActivateConstitutionRequest.SerializeToString,
                response_deserializer=control__plane_dot_v1__pb2.ActivateConstitutionResponse.FromString,
                _registered_method=True)
        self.GetActive = channel.unary_unary(
                '/yutha.control_plane.v1.ConstitutionService/GetActive',
                request_serializer=control__plane_dot_v1__pb2.GetActiveConstitutionRequest.SerializeToString,
                response_deserializer=control__plane_dot_v1__pb2.GetActiveConstitutionResponse.FromString,
                _registered_method=True)
        self.ActivateShadow = channel.unary_unary(
                '/yutha.control_plane.v1.ConstitutionService/ActivateShadow',
                request_serializer=control__plane_dot_v1__pb2.ActivateShadowConstitutionRequest.SerializeToString,
                response_deserializer=control__plane_dot_v1__pb2.ActivateShadowConstitutionResponse.FromString,
                _registered_method=True)
        self.ClearShadow = channel.unary_unary(
                '/yutha.control_plane.v1.ConstitutionService/ClearShadow',
                request_serializer=control__plane_dot_v1__pb2.ClearShadowConstitutionRequest.SerializeToString,
                response_deserializer=control__plane_dot_v1__pb2.ClearShadowConstitutionResponse.FromString,
                _registered_method=True)
        self.PromoteShadow = channel.unary_unary(
                '/yutha.control_plane.v1.ConstitutionService/PromoteShadow',
                request_serializer=control__plane_dot_v1__pb2.PromoteShadowConstitutionRequest.SerializeToString,
                response_deserializer=control__plane_dot_v1__pb2.PromoteShadowConstitutionResponse.FromString,
                _registered_method=True)
        self.GetActiveShadow = channel.unary_unary(
                '/yutha.control_plane.v1.ConstitutionService/GetActiveShadow',
                request_serializer=control__plane_dot_v1__pb2.GetActiveShadowConstitutionRequest.SerializeToString,
                response_deserializer=control__plane_dot_v1__pb2.GetActiveShadowConstitutionResponse.FromString,
                _registered_method=True)


class ConstitutionServiceServicer:
    """---------------------------------------------------------------------------
    ConstitutionService — operator publishes constitutions; agents query them
    ---------------------------------------------------------------------------

    The constitution layer (RFCs 0010-0013) lives one layer above
    capabilities: capabilities answer "who has authority"; constitutions
    answer "what authority is permitted to be exercised right now by this
    principal under our norms." Activate publishes a freshly-authored
    constitution; the active constitution is what EnvelopeService.Send
    + CapabilityService.Issue / Attenuate / Revoke evaluate against.

    Authorization: Activate requires an OperatorBearerToken (RFC 0009);
    GetActive requires any AgentBearerToken (registered agents need to
    know what they're bound to).

    """

    def Activate(self, request, context):
        """Publish a constitution. Replaces the currently-active constitution
        for the swarm. Runs the full load-time validation pass from RFC
        0012 §3.3 (structural checks, named-predicate resolution, Cedar
        Validator in Strict mode, load-time bound enforcement) before the
        activation lands. On success, a `constitution.activate` receipt
        is appended and the returned hash content-addresses the
        activated constitution.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetActive(self, request, context):
        """Fetch the currently-active constitution. Returns NOT_FOUND when
        no constitution has been activated.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ActivateShadow(self, request, context):
        """-- Shadow-mode constitution slot (Phase 3b, RFC 0018 §3.2) ----------

        The shadow slot is an operator-driven preview surface. A
        constitution loaded into the shadow slot evaluates alongside the
        active constitution on every envelope (see RFC 0018 §3.3), but
        shadow decisions only emit `constitution.evaluate.shadow.{pass,deny}`
        receipts — the active gates the cap layer + the enforcement
        engine, the shadow only observes.

        Authorization: all four shadow RPCs require an OperatorBearerToken,
        same posture as Activate. GetActiveShadow also accepts
        AgentBearerToken for read symmetry with GetActive — any registered
        agent may inspect what shadow (if any) is loaded.

        Activate a constitution into the shadow slot. Runs the same
        load-time validation pass as Activate; load-time failures surface
        immediately and never reach the hot path. Replaces any
        previously-loaded shadow without a separate clear receipt — the
        emitted `constitution.shadow_activate` receipt covers the
        activation regardless of prior slot state.

        Does NOT bind the constitution onto the enforcement engine: the
        shadow slot is observation-only per RFC 0018 §3.5.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ClearShadow(self, request, context):
        """Clear the shadow slot. Idempotent — calling against an empty
        shadow slot still emits a `constitution.shadow_clear` receipt
        (the receipt records the operator's intent regardless), but
        omits the `previously_shadowed_constitution_hash` evidence in
        the empty case.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PromoteShadow(self, request, context):
        """Promote the shadow slot to active atomically. The shadow slot
        is left empty. Emits a `constitution.shadow_promote` receipt
        (distinct from `constitution.activate` for audit clarity per
        RFC 0018 §3.2) and rebinds the enforcement engine onto the new
        active. Per-agent reputation + quarantine state is preserved
        across promote; sliding-window counters reset to match the
        existing `EnforcementEngine::activate` posture.

        Returns FAILED_PRECONDITION when the shadow slot is empty.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetActiveShadow(self, request, context):
        """Fetch the currently-loaded shadow constitution, or unset if no
        shadow is loaded. Symmetric with GetActive.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ConstitutionServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Activate': grpc.unary_unary_rpc_method_handler(
                    servicer.Activate,
                    request_deserializer=control__plane_dot_v1__pb2.ActivateConstitutionRequest.FromString,
                    response_serializer=control__plane_dot_v1__pb2.ActivateConstitutionResponse.SerializeToString,
            ),
            'GetActive': grpc.unary_unary_rpc_method_handler(
                    servicer.GetActive,
                    request_deserializer=control__plane_dot_v1__pb2.GetActiveConstitutionRequest.FromString,
                    response_serializer=control__plane_dot_v1__pb2.GetActiveConstitutionResponse.SerializeToString,
            ),
            'ActivateShadow': grpc.unary_unary_rpc_method_handler(
                    servicer.ActivateShadow,
                    request_deserializer=control__plane_dot_v1__pb2.ActivateShadowConstitutionRequest.FromString,
                    response_serializer=control__plane_dot_v1__pb2.ActivateShadowConstitutionResponse.SerializeToString,
            ),
            'ClearShadow': grpc.unary_unary_rpc_method_handler(
                    servicer.ClearShadow,
                    request_deserializer=control__plane_dot_v1__pb2.ClearShadowConstitutionRequest.FromString,
                    response_serializer=control__plane_dot_v1__pb2.ClearShadowConstitutionResponse.SerializeToString,
            ),
            'PromoteShadow': grpc.unary_unary_rpc_method_handler(
                    servicer.PromoteShadow,
                    request_deserializer=control__plane_dot_v1__pb2.PromoteShadowConstitutionRequest.FromString,
                    response_serializer=control__plane_dot_v1__pb2.PromoteShadowConstitutionResponse.SerializeToString,
            ),
            'GetActiveShadow': grpc.unary_unary_rpc_method_handler(
                    servicer.GetActiveShadow,
                    request_deserializer=control__plane_dot_v1__pb2.GetActiveShadowConstitutionRequest.FromString,
                    response_serializer=control__plane_dot_v1__pb2.GetActiveShadowConstitutionResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'yutha.control_plane.v1.ConstitutionService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('yutha.control_plane.v1.ConstitutionService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ConstitutionService:
    """---------------------------------------------------------------------------
    ConstitutionService — operator publishes constitutions; agents query them
    ---------------------------------------------------------------------------

    The constitution layer (RFCs 0010-0013) lives one layer above
    capabilities: capabilities answer "who has authority"; constitutions
    answer "what authority is permitted to be exercised right now by this
    principal under our norms." Activate publishes a freshly-authored
    constitution; the active constitution is what EnvelopeService.Send
    + CapabilityService.Issue / Attenuate / Revoke evaluate against.

    Authorization: Activate requires an OperatorBearerToken (RFC 0009);
    GetActive requires any AgentBearerToken (registered agents need to
    know what they're bound to).

    """

    @staticmethod
    def Activate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/yutha.control_plane.v1.ConstitutionService/Activate',
            control__plane_dot_v1__pb2.ActivateConstitutionRequest.SerializeToString,
            control__plane_dot_v1__pb2.ActivateConstitutionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetActive(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/yutha.control_plane.v1.ConstitutionService/GetActive',
            control__plane_dot_v1__pb2.GetActiveConstitutionRequest.SerializeToString,
            control__plane_dot_v1__pb2.GetActiveConstitutionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ActivateShadow(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/yutha.control_plane.v1.ConstitutionService/ActivateShadow',
            control__plane_dot_v1__pb2.ActivateShadowConstitutionRequest.SerializeToString,
            control__plane_dot_v1__pb2.ActivateShadowConstitutionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ClearShadow(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/yutha.control_plane.v1.ConstitutionService/ClearShadow',
            control__plane_dot_v1__pb2.ClearShadowConstitutionRequest.SerializeToString,
            control__plane_dot_v1__pb2.ClearShadowConstitutionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PromoteShadow(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/yutha.control_plane.v1.ConstitutionService/PromoteShadow',
            control__plane_dot_v1__pb2.PromoteShadowConstitutionRequest.SerializeToString,
            control__plane_dot_v1__pb2.PromoteShadowConstitutionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetActiveShadow(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/yutha.control_plane.v1.ConstitutionService/GetActiveShadow',
            control__plane_dot_v1__pb2.GetActiveShadowConstitutionRequest.SerializeToString,
            control__plane_dot_v1__pb2.GetActiveShadowConstitutionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class ReplayServiceStub:
    """---------------------------------------------------------------------------
    ReplayService — Phase 3c (RFC 0018 §4)
    ---------------------------------------------------------------------------

    Replay engine: previews a candidate constitution against a past
    receipt window. Sessions are isolated containers — each carries its
    own EnforcementEngine instance + a session-scoped ReceiptStore
    handle obtained via ReplayStore::session_store(...). Within-session
    receipts use the SAME canonical action-kinds as production but
    land in the session's isolated store and carry a replay_session_id
    evidence marker (RFC 0018 §4.3).

    Replay receipts are NEVER anchored to Sui. The AnchorDriver's
    candidate source is bound to the production receipt store only
    (RFC 0018 §4.4 — by construction).

    Authorization: all five RPCs require an OperatorBearerToken. Per
    RFC 0009 the operator id surfaces on the lifecycle audit receipts
    in the production store.

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateSession = channel.unary_unary(
                '/yutha.control_plane.v1.ReplayService/CreateSession',
                request_serializer=control__plane_dot_v1__pb2.CreateReplaySessionRequest.SerializeToString,
                response_deserializer=control__plane_dot_v1__pb2.CreateReplaySessionResponse.FromString,
                _registered_method=True)
        self.RunSession = channel.unary_stream(
                '/yutha.control_plane.v1.ReplayService/RunSession',
                request_serializer=control__plane_dot_v1__pb2.RunReplaySessionRequest.SerializeToString,
                response_deserializer=control__plane_dot_v1__pb2.ReplayProgress.FromString,
                _registered_method=True)
        self.QueryReplayReceipts = channel.unary_unary(
                '/yutha.control_plane.v1.ReplayService/QueryReplayReceipts',
                request_serializer=control__plane_dot_v1__pb2.QueryReplayReceiptsRequest.SerializeToString,
                response_deserializer=control__plane_dot_v1__pb2.QueryReplayReceiptsResponse.FromString,
                _registered_method=True)
        self.CloseSession = channel.unary_unary(
                '/yutha.control_plane.v1.ReplayService/CloseSession',
                request_serializer=control__plane_dot_v1__pb2.CloseReplaySessionRequest.SerializeToString,
                response_deserializer=control__plane_dot_v1__pb2.CloseReplaySessionResponse.FromString,
                _registered_method=True)
        self.ListSessions = channel.unary_unary(
                '/yutha.control_plane.v1.ReplayService/ListSessions',
                request_serializer=control__plane_dot_v1__pb2.ListReplaySessionsRequest.SerializeToString,
                response_deserializer=control__plane_dot_v1__pb2.ListReplaySessionsResponse.FromString,
                _registered_method=True)


class ReplayServiceServicer:
    """---------------------------------------------------------------------------
    ReplayService — Phase 3c (RFC 0018 §4)
    ---------------------------------------------------------------------------

    Replay engine: previews a candidate constitution against a past
    receipt window. Sessions are isolated containers — each carries its
    own EnforcementEngine instance + a session-scoped ReceiptStore
    handle obtained via ReplayStore::session_store(...). Within-session
    receipts use the SAME canonical action-kinds as production but
    land in the session's isolated store and carry a replay_session_id
    evidence marker (RFC 0018 §4.3).

    Replay receipts are NEVER anchored to Sui. The AnchorDriver's
    candidate source is bound to the production receipt store only
    (RFC 0018 §4.4 — by construction).

    Authorization: all five RPCs require an OperatorBearerToken. Per
    RFC 0009 the operator id surfaces on the lifecycle audit receipts
    in the production store.

    """

    def CreateSession(self, request, context):
        """Create a replay session. Instantiates the per-session
        EnforcementEngine + CedarPlusEvaluator, performs the warm-mode
        lookback rebuild if requested, and emits a
        replay.session.create audit receipt into the PRODUCTION
        receipt store.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RunSession(self, request, context):
        """Replay the receipt window against the session's candidate.
        Server-streaming: emits ReplayProgress items as the engine
        advances through the window. Operator cancellation leaves the
        session in a quiescent state — receipts replayed so far remain
        queryable until CloseSession.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def QueryReplayReceipts(self, request, context):
        """Query the session's isolated receipt store. Takes the same
        Query variants as ReceiptService.Query but evaluates them
        against the session's store. The session id must be passed
        explicitly — it is not derivable from the query.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CloseSession(self, request, context):
        """Close the session: deletes the session from the ReplayStore
        (which drops every within-session receipt), shuts down the
        per-session engine instance, and emits a
        replay.session.close audit receipt into the production store.
        Sessions also auto-close after a configurable inactivity TTL
        (default 24 hours after last RunSession activity).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListSessions(self, request, context):
        """List active replay sessions for this swarm. Scoped by the
        operator's bearer.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ReplayServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateSession': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateSession,
                    request_deserializer=control__plane_dot_v1__pb2.CreateReplaySessionRequest.FromString,
                    response_serializer=control__plane_dot_v1__pb2.CreateReplaySessionResponse.SerializeToString,
            ),
            'RunSession': grpc.unary_stream_rpc_method_handler(
                    servicer.RunSession,
                    request_deserializer=control__plane_dot_v1__pb2.RunReplaySessionRequest.FromString,
                    response_serializer=control__plane_dot_v1__pb2.ReplayProgress.SerializeToString,
            ),
            'QueryReplayReceipts': grpc.unary_unary_rpc_method_handler(
                    servicer.QueryReplayReceipts,
                    request_deserializer=control__plane_dot_v1__pb2.QueryReplayReceiptsRequest.FromString,
                    response_serializer=control__plane_dot_v1__pb2.QueryReplayReceiptsResponse.SerializeToString,
            ),
            'CloseSession': grpc.unary_unary_rpc_method_handler(
                    servicer.CloseSession,
                    request_deserializer=control__plane_dot_v1__pb2.CloseReplaySessionRequest.FromString,
                    response_serializer=control__plane_dot_v1__pb2.CloseReplaySessionResponse.SerializeToString,
            ),
            'ListSessions': grpc.unary_unary_rpc_method_handler(
                    servicer.ListSessions,
                    request_deserializer=control__plane_dot_v1__pb2.ListReplaySessionsRequest.FromString,
                    response_serializer=control__plane_dot_v1__pb2.ListReplaySessionsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'yutha.control_plane.v1.ReplayService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('yutha.control_plane.v1.ReplayService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ReplayService:
    """---------------------------------------------------------------------------
    ReplayService — Phase 3c (RFC 0018 §4)
    ---------------------------------------------------------------------------

    Replay engine: previews a candidate constitution against a past
    receipt window. Sessions are isolated containers — each carries its
    own EnforcementEngine instance + a session-scoped ReceiptStore
    handle obtained via ReplayStore::session_store(...). Within-session
    receipts use the SAME canonical action-kinds as production but
    land in the session's isolated store and carry a replay_session_id
    evidence marker (RFC 0018 §4.3).

    Replay receipts are NEVER anchored to Sui. The AnchorDriver's
    candidate source is bound to the production receipt store only
    (RFC 0018 §4.4 — by construction).

    Authorization: all five RPCs require an OperatorBearerToken. Per
    RFC 0009 the operator id surfaces on the lifecycle audit receipts
    in the production store.

    """

    @staticmethod
    def CreateSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/yutha.control_plane.v1.ReplayService/CreateSession',
            control__plane_dot_v1__pb2.CreateReplaySessionRequest.SerializeToString,
            control__plane_dot_v1__pb2.CreateReplaySessionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RunSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/yutha.control_plane.v1.ReplayService/RunSession',
            control__plane_dot_v1__pb2.RunReplaySessionRequest.SerializeToString,
            control__plane_dot_v1__pb2.ReplayProgress.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def QueryReplayReceipts(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/yutha.control_plane.v1.ReplayService/QueryReplayReceipts',
            control__plane_dot_v1__pb2.QueryReplayReceiptsRequest.SerializeToString,
            control__plane_dot_v1__pb2.QueryReplayReceiptsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CloseSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/yutha.control_plane.v1.ReplayService/CloseSession',
            control__plane_dot_v1__pb2.CloseReplaySessionRequest.SerializeToString,
            control__plane_dot_v1__pb2.CloseReplaySessionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListSessions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/yutha.control_plane.v1.ReplayService/ListSessions',
            control__plane_dot_v1__pb2.ListReplaySessionsRequest.SerializeToString,
            control__plane_dot_v1__pb2.ListReplaySessionsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
