# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from yutha._proto.control_plane import v1_pb2 as control__plane_dot_v1__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in control_plane/v1_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AdmissionServiceStub(object):
    """---------------------------------------------------------------------------
    AdmissionService — registry-facing operations
    ---------------------------------------------------------------------------

    AdmissionService handles agent lifecycle: register at swarm join,
    rotate keys, revoke. Also exposes the swarm topology (immutable for
    the swarm's lifetime — agents fetch it once and cache).
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Register = channel.unary_unary(
                '/yutha.control_plane.v1.AdmissionService/Register',
                request_serializer=control__plane_dot_v1__pb2.RegisterRequest.SerializeToString,
                response_deserializer=control__plane_dot_v1__pb2.RegisterResponse.FromString,
                _registered_method=True)
        self.Revoke = channel.unary_unary(
                '/yutha.control_plane.v1.AdmissionService/Revoke',
                request_serializer=control__plane_dot_v1__pb2.RevokeRequest.SerializeToString,
                response_deserializer=control__plane_dot_v1__pb2.RevokeResponse.FromString,
                _registered_method=True)
        self.RotateKey = channel.unary_unary(
                '/yutha.control_plane.v1.AdmissionService/RotateKey',
                request_serializer=control__plane_dot_v1__pb2.RotateKeyRequest.SerializeToString,
                response_deserializer=control__plane_dot_v1__pb2.RotateKeyResponse.FromString,
                _registered_method=True)
        self.GetTopology = channel.unary_unary(
                '/yutha.control_plane.v1.AdmissionService/GetTopology',
                request_serializer=control__plane_dot_v1__pb2.GetTopologyRequest.SerializeToString,
                response_deserializer=control__plane_dot_v1__pb2.GetTopologyResponse.FromString,
                _registered_method=True)


class AdmissionServiceServicer(object):
    """---------------------------------------------------------------------------
    AdmissionService — registry-facing operations
    ---------------------------------------------------------------------------

    AdmissionService handles agent lifecycle: register at swarm join,
    rotate keys, revoke. Also exposes the swarm topology (immutable for
    the swarm's lifetime — agents fetch it once and cache).
    """

    def Register(self, request, context):
        """Register an agent presenting a signed passport. The control plane
        verifies the passport's self-signature, evaluates admission policy
        against the topology, and (on accept) produces an `agent.register`
        receipt. The response carries the receipt id; the agent can fetch
        the receipt via ReceiptService.Get.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Revoke(self, request, context):
        """Revoke an agent. The caller MUST be either the agent itself
        (self-revoke) or an operator-level identity. Produces an
        `agent.revoke` receipt.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RotateKey(self, request, context):
        """Rotate an agent's signing key. Produces an `agent.rotate_key`
        receipt. Future tokens / envelopes / capabilities signed by the
        agent MUST use the new key starting from the receipt's monotonic_ns.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTopology(self, request, context):
        """Get the topology of the swarm this control plane manages. Topology
        is immutable for a swarm's lifetime; agents call this once at
        startup and cache the result.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AdmissionServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Register': grpc.unary_unary_rpc_method_handler(
                    servicer.Register,
                    request_deserializer=control__plane_dot_v1__pb2.RegisterRequest.FromString,
                    response_serializer=control__plane_dot_v1__pb2.RegisterResponse.SerializeToString,
            ),
            'Revoke': grpc.unary_unary_rpc_method_handler(
                    servicer.Revoke,
                    request_deserializer=control__plane_dot_v1__pb2.RevokeRequest.FromString,
                    response_serializer=control__plane_dot_v1__pb2.RevokeResponse.SerializeToString,
            ),
            'RotateKey': grpc.unary_unary_rpc_method_handler(
                    servicer.RotateKey,
                    request_deserializer=control__plane_dot_v1__pb2.RotateKeyRequest.FromString,
                    response_serializer=control__plane_dot_v1__pb2.RotateKeyResponse.SerializeToString,
            ),
            'GetTopology': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTopology,
                    request_deserializer=control__plane_dot_v1__pb2.GetTopologyRequest.FromString,
                    response_serializer=control__plane_dot_v1__pb2.GetTopologyResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'yutha.control_plane.v1.AdmissionService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('yutha.control_plane.v1.AdmissionService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AdmissionService(object):
    """---------------------------------------------------------------------------
    AdmissionService — registry-facing operations
    ---------------------------------------------------------------------------

    AdmissionService handles agent lifecycle: register at swarm join,
    rotate keys, revoke. Also exposes the swarm topology (immutable for
    the swarm's lifetime — agents fetch it once and cache).
    """

    @staticmethod
    def Register(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/yutha.control_plane.v1.AdmissionService/Register',
            control__plane_dot_v1__pb2.RegisterRequest.SerializeToString,
            control__plane_dot_v1__pb2.RegisterResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Revoke(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/yutha.control_plane.v1.AdmissionService/Revoke',
            control__plane_dot_v1__pb2.RevokeRequest.SerializeToString,
            control__plane_dot_v1__pb2.RevokeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RotateKey(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/yutha.control_plane.v1.AdmissionService/RotateKey',
            control__plane_dot_v1__pb2.RotateKeyRequest.SerializeToString,
            control__plane_dot_v1__pb2.RotateKeyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetTopology(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/yutha.control_plane.v1.AdmissionService/GetTopology',
            control__plane_dot_v1__pb2.GetTopologyRequest.SerializeToString,
            control__plane_dot_v1__pb2.GetTopologyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class CapabilityServiceStub(object):
    """---------------------------------------------------------------------------
    CapabilityService — issue, attenuate, revoke, check
    ---------------------------------------------------------------------------

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Issue = channel.unary_unary(
                '/yutha.control_plane.v1.CapabilityService/Issue',
                request_serializer=control__plane_dot_v1__pb2.IssueCapabilityRequest.SerializeToString,
                response_deserializer=control__plane_dot_v1__pb2.IssueCapabilityResponse.FromString,
                _registered_method=True)
        self.Attenuate = channel.unary_unary(
                '/yutha.control_plane.v1.CapabilityService/Attenuate',
                request_serializer=control__plane_dot_v1__pb2.AttenuateRequest.SerializeToString,
                response_deserializer=control__plane_dot_v1__pb2.AttenuateResponse.FromString,
                _registered_method=True)
        self.Revoke = channel.unary_unary(
                '/yutha.control_plane.v1.CapabilityService/Revoke',
                request_serializer=control__plane_dot_v1__pb2.RevokeCapabilityRequest.SerializeToString,
                response_deserializer=control__plane_dot_v1__pb2.RevokeCapabilityResponse.FromString,
                _registered_method=True)
        self.Check = channel.unary_unary(
                '/yutha.control_plane.v1.CapabilityService/Check',
                request_serializer=control__plane_dot_v1__pb2.CheckRequest.SerializeToString,
                response_deserializer=control__plane_dot_v1__pb2.CheckResponse.FromString,
                _registered_method=True)


class CapabilityServiceServicer(object):
    """---------------------------------------------------------------------------
    CapabilityService — issue, attenuate, revoke, check
    ---------------------------------------------------------------------------

    """

    def Issue(self, request, context):
        """Issue a new (root or attenuated) capability. Issuer authority is
        checked against the bearer token: operators can mint root caps;
        agents can attenuate from caps they hold.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Attenuate(self, request, context):
        """Attenuate an existing capability into a more restricted child. The
        child's scope is intersected with the parent's, caveats are
        additive, and `valid_until` cannot exceed the parent's.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Revoke(self, request, context):
        """Revoke a capability. Effective immediately for the control plane's
        own checks; propagation to federation peers is on a TTL.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Check(self, request, context):
        """Check whether a (capability, action) pair is permitted. Stateless,
        deterministic. Mostly used by SDKs for client-side pre-flight; the
        control plane still re-checks on every Send.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CapabilityServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Issue': grpc.unary_unary_rpc_method_handler(
                    servicer.Issue,
                    request_deserializer=control__plane_dot_v1__pb2.IssueCapabilityRequest.FromString,
                    response_serializer=control__plane_dot_v1__pb2.IssueCapabilityResponse.SerializeToString,
            ),
            'Attenuate': grpc.unary_unary_rpc_method_handler(
                    servicer.Attenuate,
                    request_deserializer=control__plane_dot_v1__pb2.AttenuateRequest.FromString,
                    response_serializer=control__plane_dot_v1__pb2.AttenuateResponse.SerializeToString,
            ),
            'Revoke': grpc.unary_unary_rpc_method_handler(
                    servicer.Revoke,
                    request_deserializer=control__plane_dot_v1__pb2.RevokeCapabilityRequest.FromString,
                    response_serializer=control__plane_dot_v1__pb2.RevokeCapabilityResponse.SerializeToString,
            ),
            'Check': grpc.unary_unary_rpc_method_handler(
                    servicer.Check,
                    request_deserializer=control__plane_dot_v1__pb2.CheckRequest.FromString,
                    response_serializer=control__plane_dot_v1__pb2.CheckResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'yutha.control_plane.v1.CapabilityService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('yutha.control_plane.v1.CapabilityService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CapabilityService(object):
    """---------------------------------------------------------------------------
    CapabilityService — issue, attenuate, revoke, check
    ---------------------------------------------------------------------------

    """

    @staticmethod
    def Issue(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/yutha.control_plane.v1.CapabilityService/Issue',
            control__plane_dot_v1__pb2.IssueCapabilityRequest.SerializeToString,
            control__plane_dot_v1__pb2.IssueCapabilityResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Attenuate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/yutha.control_plane.v1.CapabilityService/Attenuate',
            control__plane_dot_v1__pb2.AttenuateRequest.SerializeToString,
            control__plane_dot_v1__pb2.AttenuateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Revoke(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/yutha.control_plane.v1.CapabilityService/Revoke',
            control__plane_dot_v1__pb2.RevokeCapabilityRequest.SerializeToString,
            control__plane_dot_v1__pb2.RevokeCapabilityResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Check(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/yutha.control_plane.v1.CapabilityService/Check',
            control__plane_dot_v1__pb2.CheckRequest.SerializeToString,
            control__plane_dot_v1__pb2.CheckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class EnvelopeServiceStub(object):
    """---------------------------------------------------------------------------
    EnvelopeService — typed messaging
    ---------------------------------------------------------------------------

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Send = channel.unary_unary(
                '/yutha.control_plane.v1.EnvelopeService/Send',
                request_serializer=control__plane_dot_v1__pb2.SendEnvelopeRequest.SerializeToString,
                response_deserializer=control__plane_dot_v1__pb2.SendEnvelopeResponse.FromString,
                _registered_method=True)
        self.Subscribe = channel.unary_stream(
                '/yutha.control_plane.v1.EnvelopeService/Subscribe',
                request_serializer=control__plane_dot_v1__pb2.SubscribeRequest.SerializeToString,
                response_deserializer=control__plane_dot_v1__pb2.SubscribedEnvelope.FromString,
                _registered_method=True)


class EnvelopeServiceServicer(object):
    """---------------------------------------------------------------------------
    EnvelopeService — typed messaging
    ---------------------------------------------------------------------------

    """

    def Send(self, request, context):
        """Submit a signed envelope for delivery. The control plane:
        1. Verifies the envelope's actor signature against the agent's
        registered passport public key.
        2. Capability-checks the action (envelope.send) against the
        agent's held capabilities.
        3. Persists an `envelope.send` receipt.
        4. Forwards to the recipient's subscribe stream (if any).
        5. On successful delivery, persists an `envelope.deliver` receipt.

        The response carries the send-receipt id immediately; the
        deliver-receipt arrives asynchronously and can be polled via
        ReceiptService.Query.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Subscribe(self, request, context):
        """Subscribe to envelopes addressed to the calling agent. The stream
        stays open; envelopes arrive as they are delivered to the agent.
        Cancelling the stream means "I'm no longer subscribed" — the
        control plane stops forwarding and may buffer per the topology's
        delivery policy.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_EnvelopeServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Send': grpc.unary_unary_rpc_method_handler(
                    servicer.Send,
                    request_deserializer=control__plane_dot_v1__pb2.SendEnvelopeRequest.FromString,
                    response_serializer=control__plane_dot_v1__pb2.SendEnvelopeResponse.SerializeToString,
            ),
            'Subscribe': grpc.unary_stream_rpc_method_handler(
                    servicer.Subscribe,
                    request_deserializer=control__plane_dot_v1__pb2.SubscribeRequest.FromString,
                    response_serializer=control__plane_dot_v1__pb2.SubscribedEnvelope.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'yutha.control_plane.v1.EnvelopeService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('yutha.control_plane.v1.EnvelopeService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class EnvelopeService(object):
    """---------------------------------------------------------------------------
    EnvelopeService — typed messaging
    ---------------------------------------------------------------------------

    """

    @staticmethod
    def Send(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/yutha.control_plane.v1.EnvelopeService/Send',
            control__plane_dot_v1__pb2.SendEnvelopeRequest.SerializeToString,
            control__plane_dot_v1__pb2.SendEnvelopeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Subscribe(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/yutha.control_plane.v1.EnvelopeService/Subscribe',
            control__plane_dot_v1__pb2.SubscribeRequest.SerializeToString,
            control__plane_dot_v1__pb2.SubscribedEnvelope.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class ReceiptServiceStub(object):
    """---------------------------------------------------------------------------
    ReceiptService — read access to the audit log
    ---------------------------------------------------------------------------

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Get = channel.unary_unary(
                '/yutha.control_plane.v1.ReceiptService/Get',
                request_serializer=control__plane_dot_v1__pb2.GetReceiptRequest.SerializeToString,
                response_deserializer=control__plane_dot_v1__pb2.GetReceiptResponse.FromString,
                _registered_method=True)
        self.Query = channel.unary_unary(
                '/yutha.control_plane.v1.ReceiptService/Query',
                request_serializer=control__plane_dot_v1__pb2.QueryReceiptsRequest.SerializeToString,
                response_deserializer=control__plane_dot_v1__pb2.QueryReceiptsResponse.FromString,
                _registered_method=True)


class ReceiptServiceServicer(object):
    """---------------------------------------------------------------------------
    ReceiptService — read access to the audit log
    ---------------------------------------------------------------------------

    """

    def Get(self, request, context):
        """Fetch a single receipt by content-address.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Query(self, request, context):
        """Run a structured query against the receipt store. Supports the same
        query variants as the receipt store trait (by-id, by-predecessor,
        by-agent, by-action-kind, by-time-range), with keyset pagination
        via opaque page tokens.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ReceiptServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Get': grpc.unary_unary_rpc_method_handler(
                    servicer.Get,
                    request_deserializer=control__plane_dot_v1__pb2.GetReceiptRequest.FromString,
                    response_serializer=control__plane_dot_v1__pb2.GetReceiptResponse.SerializeToString,
            ),
            'Query': grpc.unary_unary_rpc_method_handler(
                    servicer.Query,
                    request_deserializer=control__plane_dot_v1__pb2.QueryReceiptsRequest.FromString,
                    response_serializer=control__plane_dot_v1__pb2.QueryReceiptsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'yutha.control_plane.v1.ReceiptService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('yutha.control_plane.v1.ReceiptService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ReceiptService(object):
    """---------------------------------------------------------------------------
    ReceiptService — read access to the audit log
    ---------------------------------------------------------------------------

    """

    @staticmethod
    def Get(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/yutha.control_plane.v1.ReceiptService/Get',
            control__plane_dot_v1__pb2.GetReceiptRequest.SerializeToString,
            control__plane_dot_v1__pb2.GetReceiptResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Query(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/yutha.control_plane.v1.ReceiptService/Query',
            control__plane_dot_v1__pb2.QueryReceiptsRequest.SerializeToString,
            control__plane_dot_v1__pb2.QueryReceiptsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
