//! Markdown renderer.
//!
//! Human-readable diff output suitable for pasting into PR review
//! threads. Section order matches [`crate::model::ConstitutionDiff`]
//! field order:
//!
//! 1. Document title with constitution-version transition.
//! 2. Summary line per section (counts).
//! 3. Schema-version change (if any).
//! 4. Cedar policies — Added / Removed / Modified subsections,
//!    with the un-annotated-policies hint riding above when
//!    present.
//! 5. Named predicates / Scoring rules / Procedures / Enforcement
//!    rules — same Added / Removed / Modified shape; each value
//!    rendered as a YAML-flavoured JSON code block (the underlying
//!    engine-config types derive `Serialize`, so the structured
//!    fields render cleanly).
//! 6. Behavioural diff (when present) — receipt-count deltas table
//!    + enforcement chain divergences table.
//!
//! Empty sections collapse to `_(no changes)_` rather than being
//! elided — shape stability is more important than terseness for
//! review-thread use.

use std::io::Write;

use crate::behavioural::BehaviouralDiff;
use crate::cedar::{has_unannotated_policies, CedarPolicyEntry};
use crate::error::Result;
use crate::model::{ConstitutionDiff, NamedItemChange, NamedItemsDiff};

pub(crate) fn render(diff: &ConstitutionDiff, out: &mut impl Write) -> Result<()> {
    write_title(diff, out)?;
    write_summary(diff, out)?;
    write_schema_version_change(diff, out)?;
    write_cedar_policies_section(&diff.cedar_policies, out)?;
    write_named_section(
        "Named predicates",
        &diff.named_predicates,
        |p| p.name.clone(),
        out,
    )?;
    write_named_section(
        "Scoring rules",
        &diff.scoring_rules,
        |r| r.name.clone(),
        out,
    )?;
    write_named_section("Procedures", &diff.procedures, |p| p.name.clone(), out)?;
    write_named_section(
        "Enforcement rules",
        &diff.enforcement_rules,
        |r| r.name.clone(),
        out,
    )?;
    if let Some(b) = &diff.behavioural {
        write_behavioural_section(b, out)?;
    }
    Ok(())
}

// ---------------------------------------------------------------------------
// section writers
// ---------------------------------------------------------------------------

fn write_title(diff: &ConstitutionDiff, out: &mut impl Write) -> Result<()> {
    writeln!(
        out,
        "# Constitution diff ({} \u{2192} {})",
        diff.left_constitution_version, diff.right_constitution_version
    )?;
    writeln!(out)?;
    writeln!(
        out,
        "_Generated by yutha-diff (schema {}). Empty sections render as `(no changes)`._",
        diff.diff_schema_version
    )?;
    writeln!(out)?;
    Ok(())
}

fn write_summary(diff: &ConstitutionDiff, out: &mut impl Write) -> Result<()> {
    writeln!(out, "## Summary")?;
    writeln!(out)?;

    if diff.is_empty_structurally() && diff.behavioural.is_none() {
        writeln!(out, "_(no changes)_")?;
        writeln!(out)?;
        return Ok(());
    }

    if let Some((from, to)) = &diff.schema_version_change {
        writeln!(out, "- Schema version: `{from}` \u{2192} `{to}`")?;
    }
    writeln!(
        out,
        "- Cedar policies: {}",
        summarise_counts(&diff.cedar_policies)
    )?;
    writeln!(
        out,
        "- Named predicates: {}",
        summarise_counts(&diff.named_predicates)
    )?;
    writeln!(
        out,
        "- Scoring rules: {}",
        summarise_counts(&diff.scoring_rules)
    )?;
    writeln!(out, "- Procedures: {}", summarise_counts(&diff.procedures))?;
    writeln!(
        out,
        "- Enforcement rules: {}",
        summarise_counts(&diff.enforcement_rules)
    )?;
    if let Some(b) = &diff.behavioural {
        writeln!(
            out,
            "- Behavioural: {} receipt-count deltas, {} chain divergences (window \
             {} \u{2192} {})",
            b.receipt_count_deltas.len(),
            b.chain_divergences.len(),
            b.window_from_unix_ns,
            b.window_to_unix_ns
        )?;
    }
    writeln!(out)?;
    Ok(())
}

fn summarise_counts<T>(section: &NamedItemsDiff<T>) -> String {
    if section.is_empty() {
        return "(no changes)".to_string();
    }
    format!(
        "{} added, {} removed, {} modified",
        section.added.len(),
        section.removed.len(),
        section.modified.len()
    )
}

fn write_schema_version_change(diff: &ConstitutionDiff, out: &mut impl Write) -> Result<()> {
    writeln!(out, "## Schema version")?;
    writeln!(out)?;
    match &diff.schema_version_change {
        Some((from, to)) => writeln!(out, "Pin changed: `{from}` \u{2192} `{to}`.")?,
        None => writeln!(out, "_(no changes)_")?,
    }
    writeln!(out)?;
    Ok(())
}

fn write_cedar_policies_section(
    section: &NamedItemsDiff<CedarPolicyEntry>,
    out: &mut impl Write,
) -> Result<()> {
    writeln!(out, "## Cedar policies")?;
    writeln!(out)?;

    let any_unannotated = has_unannotated_policies(&section.added)
        || has_unannotated_policies(&section.removed)
        || section
            .modified
            .iter()
            .any(|m| !m.left.annotated || !m.right.annotated);
    if any_unannotated {
        writeln!(
            out,
            "> **Note:** un-annotated Cedar policies were encountered. Consider adding \
             `@id(\"...\")` annotations so diffs key on the operator-supplied name rather \
             than a structural fingerprint."
        )?;
        writeln!(out)?;
    }

    write_cedar_subsection("Added", &section.added, out)?;
    write_cedar_subsection("Removed", &section.removed, out)?;
    write_cedar_modified(&section.modified, out)?;
    Ok(())
}

fn write_cedar_subsection(
    label: &str,
    entries: &[CedarPolicyEntry],
    out: &mut impl Write,
) -> Result<()> {
    writeln!(out, "### {label} ({})", entries.len())?;
    writeln!(out)?;
    if entries.is_empty() {
        writeln!(out, "_(none)_")?;
        writeln!(out)?;
        return Ok(());
    }
    for entry in entries {
        let annotation = if entry.annotated {
            "annotated"
        } else {
            "un-annotated"
        };
        writeln!(
            out,
            "#### `{}` ({}, {annotation})",
            entry.name, entry.effect
        )?;
        writeln!(out)?;
        writeln!(out, "```cedar")?;
        write!(out, "{}", entry.source)?;
        if !entry.source.ends_with('\n') {
            writeln!(out)?;
        }
        writeln!(out, "```")?;
        writeln!(out)?;
    }
    Ok(())
}

fn write_cedar_modified(
    entries: &[NamedItemChange<CedarPolicyEntry>],
    out: &mut impl Write,
) -> Result<()> {
    writeln!(out, "### Modified ({})", entries.len())?;
    writeln!(out)?;
    if entries.is_empty() {
        writeln!(out, "_(none)_")?;
        writeln!(out)?;
        return Ok(());
    }
    for change in entries {
        writeln!(
            out,
            "#### `{}` ({}, was {})",
            change.name, change.right.effect, change.left.effect
        )?;
        writeln!(out)?;
        writeln!(out, "**Before:**")?;
        writeln!(out)?;
        writeln!(out, "```cedar")?;
        write!(out, "{}", change.left.source)?;
        if !change.left.source.ends_with('\n') {
            writeln!(out)?;
        }
        writeln!(out, "```")?;
        writeln!(out)?;
        writeln!(out, "**After:**")?;
        writeln!(out)?;
        writeln!(out, "```cedar")?;
        write!(out, "{}", change.right.source)?;
        if !change.right.source.ends_with('\n') {
            writeln!(out)?;
        }
        writeln!(out, "```")?;
        writeln!(out)?;
    }
    Ok(())
}

fn write_named_section<T, KeyFn>(
    title: &str,
    section: &NamedItemsDiff<T>,
    name_of: KeyFn,
    out: &mut impl Write,
) -> Result<()>
where
    T: serde::Serialize,
    KeyFn: Fn(&T) -> String,
{
    writeln!(out, "## {title}")?;
    writeln!(out)?;
    if section.is_empty() {
        writeln!(out, "_(no changes)_")?;
        writeln!(out)?;
        return Ok(());
    }

    write_named_subsection("Added", &section.added, &name_of, out)?;
    write_named_subsection("Removed", &section.removed, &name_of, out)?;
    write_named_modified(&section.modified, out)?;
    Ok(())
}

fn write_named_subsection<T, KeyFn>(
    label: &str,
    entries: &[T],
    name_of: &KeyFn,
    out: &mut impl Write,
) -> Result<()>
where
    T: serde::Serialize,
    KeyFn: Fn(&T) -> String,
{
    writeln!(out, "### {label} ({})", entries.len())?;
    writeln!(out)?;
    if entries.is_empty() {
        writeln!(out, "_(none)_")?;
        writeln!(out)?;
        return Ok(());
    }
    for entry in entries {
        let name = name_of(entry);
        writeln!(out, "#### `{name}`")?;
        writeln!(out)?;
        writeln!(out, "```json")?;
        let pretty = serde_json::to_string_pretty(entry)?;
        writeln!(out, "{pretty}")?;
        writeln!(out, "```")?;
        writeln!(out)?;
    }
    Ok(())
}

fn write_named_modified<T>(entries: &[NamedItemChange<T>], out: &mut impl Write) -> Result<()>
where
    T: serde::Serialize,
{
    writeln!(out, "### Modified ({})", entries.len())?;
    writeln!(out)?;
    if entries.is_empty() {
        writeln!(out, "_(none)_")?;
        writeln!(out)?;
        return Ok(());
    }
    for change in entries {
        writeln!(out, "#### `{}`", change.name)?;
        writeln!(out)?;
        writeln!(out, "**Before:**")?;
        writeln!(out)?;
        writeln!(out, "```json")?;
        let pretty_left = serde_json::to_string_pretty(&change.left)?;
        writeln!(out, "{pretty_left}")?;
        writeln!(out, "```")?;
        writeln!(out)?;
        writeln!(out, "**After:**")?;
        writeln!(out)?;
        writeln!(out, "```json")?;
        let pretty_right = serde_json::to_string_pretty(&change.right)?;
        writeln!(out, "{pretty_right}")?;
        writeln!(out, "```")?;
        writeln!(out)?;
    }
    Ok(())
}

fn write_behavioural_section(b: &BehaviouralDiff, out: &mut impl Write) -> Result<()> {
    writeln!(
        out,
        "## Behavioural diff (window {} \u{2192} {})",
        b.window_from_unix_ns, b.window_to_unix_ns
    )?;
    writeln!(out)?;
    writeln!(
        out,
        "_Replay session id: `{}`. Counts compare the production receipt store \
         against the candidate's session-scoped store over the same window._",
        b.replay_session_id
    )?;
    writeln!(out)?;

    writeln!(out, "### Receipt count deltas")?;
    writeln!(out)?;
    if b.receipt_count_deltas.is_empty() {
        writeln!(out, "_(none)_")?;
        writeln!(out)?;
    } else {
        writeln!(
            out,
            "| action_kind | subject_agent_id | production | candidate | delta |"
        )?;
        writeln!(
            out,
            "|-------------|------------------|-----------:|----------:|------:|"
        )?;
        for d in &b.receipt_count_deltas {
            writeln!(
                out,
                "| `{}` | `{}` | {} | {} | {} |",
                d.action_kind,
                if d.subject_agent_id.is_empty() {
                    "(none)"
                } else {
                    &d.subject_agent_id
                },
                d.production_count,
                d.candidate_count,
                format_signed_delta(d.delta()),
            )?;
        }
        writeln!(out)?;
    }

    writeln!(out, "### Enforcement chain divergences")?;
    writeln!(out)?;
    if b.chain_divergences.is_empty() {
        writeln!(out, "_(none)_")?;
        writeln!(out)?;
    } else {
        writeln!(
            out,
            "| target_agent_id | enforcement_rule_id | stage | production | candidate | delta |"
        )?;
        writeln!(
            out,
            "|-----------------|---------------------|-------|-----------:|----------:|------:|"
        )?;
        for c in &b.chain_divergences {
            writeln!(
                out,
                "| `{}` | `{}` | `{}` | {} | {} | {} |",
                c.target_agent_id,
                c.enforcement_rule_id,
                c.stage,
                c.production_count,
                c.candidate_count,
                format_signed_delta(c.delta()),
            )?;
        }
        writeln!(out)?;
    }
    Ok(())
}

fn format_signed_delta(d: i64) -> String {
    if d >= 0 {
        format!("+{d}")
    } else {
        format!("{d}")
    }
}

// ---------------------------------------------------------------------------
// tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;
    use crate::behavioural::{ChainDivergence, ReceiptCountDelta};
    use crate::cedar::CedarPolicyEffect;
    use crate::diff::DIFF_SCHEMA_VERSION;

    fn empty_diff() -> ConstitutionDiff {
        ConstitutionDiff {
            diff_schema_version: DIFF_SCHEMA_VERSION.to_string(),
            left_constitution_version: "1.0.0".into(),
            right_constitution_version: "1.0.0".into(),
            schema_version_change: None,
            cedar_policies: NamedItemsDiff::default(),
            named_predicates: NamedItemsDiff::default(),
            scoring_rules: NamedItemsDiff::default(),
            procedures: NamedItemsDiff::default(),
            enforcement_rules: NamedItemsDiff::default(),
            behavioural: None,
        }
    }

    fn render_to_string(diff: &ConstitutionDiff) -> String {
        let mut buf = Vec::new();
        render(diff, &mut buf).expect("render");
        String::from_utf8(buf).expect("utf8")
    }

    #[test]
    fn empty_diff_shows_no_changes_per_section() {
        let s = render_to_string(&empty_diff());
        // Title with the version transition.
        assert!(s.contains("# Constitution diff (1.0.0 \u{2192} 1.0.0)"));
        // Top-level summary is the single no-changes line.
        assert!(s.contains("## Summary"));
        // All five section headers render even when empty.
        for h in [
            "## Cedar policies",
            "## Named predicates",
            "## Scoring rules",
            "## Procedures",
            "## Enforcement rules",
        ] {
            assert!(s.contains(h), "missing section header {h:?}\n--\n{s}");
        }
        // Behavioural section absent for static-only diffs.
        assert!(
            !s.contains("## Behavioural"),
            "behavioural section MUST be elided for static-only diffs:\n{s}"
        );
    }

    #[test]
    fn added_cedar_policy_renders_inline_source() {
        let mut diff = empty_diff();
        diff.cedar_policies.added.push(CedarPolicyEntry::new(
            "no-x",
            true,
            CedarPolicyEffect::Forbid,
            "@id(\"no-x\")\nforbid (principal, action, resource);",
        ));
        let s = render_to_string(&diff);
        assert!(s.contains("### Added (1)"));
        assert!(s.contains("#### `no-x` (forbid, annotated)"));
        assert!(s.contains("```cedar"));
        assert!(s.contains("@id(\"no-x\")"));
        // Per-section summary count.
        assert!(s.contains("Cedar policies: 1 added, 0 removed, 0 modified"));
    }

    #[test]
    fn unannotated_hint_surfaces_when_present() {
        let mut diff = empty_diff();
        diff.cedar_policies.added.push(CedarPolicyEntry::new(
            "permit:fingerprint",
            false,
            CedarPolicyEffect::Permit,
            "permit (principal, action, resource);",
        ));
        let s = render_to_string(&diff);
        assert!(s.contains("> **Note:** un-annotated Cedar policies"));
        assert!(s.contains("(permit, un-annotated)"));
    }

    #[test]
    fn behavioural_section_renders_when_present() {
        let mut diff = empty_diff();
        diff.behavioural = Some(BehaviouralDiff {
            window_from_unix_ns: 1_000,
            window_to_unix_ns: 2_000,
            replay_session_id: "session-uuid".into(),
            receipt_count_deltas: vec![ReceiptCountDelta {
                action_kind: "constitution.evaluate.deny".into(),
                subject_agent_id: "alice".into(),
                production_count: 12,
                candidate_count: 18,
            }],
            chain_divergences: vec![ChainDivergence {
                target_agent_id: "alice".into(),
                enforcement_rule_id: "forbidden_payload_chain".into(),
                stage: "detect".into(),
                production_count: 0,
                candidate_count: 1,
            }],
        });
        let s = render_to_string(&diff);
        assert!(s.contains("## Behavioural diff (window 1000 \u{2192} 2000)"));
        assert!(s.contains("session-uuid"));
        // Table headers.
        assert!(s.contains("| action_kind | subject_agent_id"));
        assert!(s.contains("| target_agent_id | enforcement_rule_id"));
        // Signed delta formatting.
        assert!(s.contains("+6"));
        assert!(s.contains("+1"));
    }

    #[test]
    fn modified_engine_config_item_renders_before_after() {
        use yutha_cedar_plus::engine_config::NamedPredicate;
        let mut diff = empty_diff();
        diff.named_predicates.modified.push(NamedItemChange {
            name: "is_supervisor".into(),
            left: NamedPredicate {
                name: "is_supervisor".into(),
                expr: "principal.role == \"supervisor\"".into(),
            },
            right: NamedPredicate {
                name: "is_supervisor".into(),
                expr: "principal.role == \"admin\"".into(),
            },
        });
        let s = render_to_string(&diff);
        assert!(s.contains("## Named predicates"));
        assert!(s.contains("### Modified (1)"));
        assert!(s.contains("#### `is_supervisor`"));
        assert!(s.contains("**Before:**"));
        assert!(s.contains("**After:**"));
        // The expr string is wrapped in JSON, which escapes the
        // inner quotes around `supervisor` / `admin` to `\"...\"`.
        // Assert on the plain word to avoid coupling to escape
        // shape.
        assert!(s.contains("supervisor"));
        assert!(s.contains("admin"));
    }
}
